# Generated by Django 5.0.2 on 2024-02-14 07:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_item_slug_order_ordered'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='orderitem',
            name='ordered',
        ),
        migrations.RemoveField(
            model_name='orderitem',
            name='user',
        ),
    ]
